version: "3.9"
services:
  bot:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SHODAN_API_KEY
      - SLACK_WEBHOOK_URL
    image: timkoopmans/eipbot
  slackbot:
    build: ./slack
    environment:
      - SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN
      - PYTHONUNBUFFERED
    image: timkoopmans/eipbot-slack